/*
  # Update daily_content with correct videos and questions

  Replaces all placeholder data with the real content for days 0-22:
  - Correct YouTube embed URLs per day
  - Real daily quotes
  - Specific reflection questions per day
  - Insight prompts per day
  - Stage names per day
*/

INSERT INTO public.daily_content (day_number, stage_name, video_embed_url, daily_quote, questions_text, insight_prompt_text, is_published)
VALUES
(0, 'Bienvenida', '<iframe width="315" height="576" src="https://www.youtube.com/embed/GUAPahWgpFo" frameborder="0" allowfullscreen></iframe>', 'El viaje de mil millas comienza con un solo paso.', E'1. ¿Qué te trae aquí hoy?\n2. ¿Qué esperas descubrir sobre ti mismo?\n3. ¿Qué compromiso haces contigo mismo?', 'Escribe cómo te sientes al comenzar esta bitácora.', true),
(1, 'Desmitificación Radical', '<iframe width="315" height="576" src="https://www.youtube.com/embed/cowU546apVc" frameborder="0" allowfullscreen></iframe>', 'El éxito externo no garantiza plenitud interna.', E'1. ¿Qué áreas de tu vida funcionan?\n2. ¿Qué parte de tu vida se ve bien por fuera... pero se siente vacía por dentro?\n3. Si fueras completamente libre... ¿qué cambiarías?', '¿Qué aprendiste sobre tu vida hoy?', true),
(2, 'Desmitificación Radical', '<iframe width="315" height="576" src="https://www.youtube.com/embed/huu6z8vvHRs" frameborder="0" allowfullscreen></iframe>', 'Muchas vidas son una actuación perfectamente exitosa.', E'1. ¿Quién eras antes de sentir que tenías que ser alguien?\n2. ¿En qué momento empezaste a esconder partes de ti?\n3. ¿Qué personaje interpretas hoy?', '¿Qué descubriste sobre tu autenticidad?', true),
(3, 'Desmitificación Radical', '<iframe width="315" height="576" src="https://www.youtube.com/embed/4Y1s5bqigpQ" frameborder="0" allowfullscreen></iframe>', 'Lo que no sueltas, te arrastra.', E'1. ¿Qué estás sosteniendo que ya no te sirve?\n2. ¿Qué temes que pase si lo sueltas?\n3. ¿Qué te está costando seguir sosteniéndolo?', '¿Qué peso puedes empezar a soltar?', true),
(4, 'Desmitificación Radical', '<iframe width="315" height="576" src="https://www.youtube.com/embed/UaAopsvn70U" frameborder="0" allowfullscreen></iframe>', 'Lo que escondes no desaparece: se vuelve síntoma.', E'1. ¿Qué imagen de ti intentas sostener?\n2. ¿Qué parte de ti no te permites mostrar?\n3. ¿Qué te cuesta seguir escondiendo?', '¿Qué máscara reconociste hoy?', true),
(5, 'Desmitificación Radical', '<iframe width="315" height="576" src="https://www.youtube.com/embed/q9TJqfa680c" frameborder="0" allowfullscreen></iframe>', 'No eres tu historia, eres quien la interpreta.', E'1. "La historia que me conté para sobrevivir."\n2. "La verdad que hoy estoy dispuesto a aceptar."\n3. "La historia que elijo contar a partir de hoy."', '¿Qué nueva historia eliges?', true),
(6, 'Exploración Auténtica', '<iframe width="315" height="576" src="https://www.youtube.com/embed/9isC62znFLY" frameborder="0" allowfullscreen></iframe>', 'El DESEO no es un capricho, es dirección.', E'1. ¿Cuándo fue la última vez que te sentiste profundamente vivo?\n2. ¿Qué actividades te hacen perder la noción del tiempo?\n3. Si nadie te juzgara... ¿qué te permitirías explorar?', '¿Qué deseo auténtico está emergiendo?', true),
(7, 'Exploración Auténtica', '<iframe width="315" height="576" src="https://www.youtube.com/embed/wZ1D9nB7LW8" frameborder="0" allowfullscreen></iframe>', 'Tu cuerpo sabe lo que tu mente no puede explicar.', E'1. ¿Qué personas te expanden?\n2. ¿Qué actividades te expanden?\n3. ¿Qué situaciones te contraen?', '¿Qué aprendiste al observar tu energía?', true),
(8, 'Exploración Auténtica', '<iframe width="315" height="576" src="https://www.youtube.com/embed/R08I4_H8PF0" frameborder="0" allowfullscreen></iframe>', 'El DESEO camina junto al miedo.', E'1. ¿Qué sería de ti si eliminas la palabra "debería"?\n2. ¿Qué parte de ti se activa al escribirlo?\n3. ¿Qué harías diferente esta semana?', '¿Qué miedo está protegiendo tu deseo?', true),
(9, 'Exploración Auténtica', '<iframe width="315" height="576" src="https://www.youtube.com/embed/cfPiIS5WycA" frameborder="0" allowfullscreen></iframe>', 'Donde hay miedo, suele haber crecimiento real.', E'1. ¿Qué es lo que más te asusta de aquello que deseas?\n2. ¿Qué intenta proteger ese miedo?\n3. ¿Qué paso pequeño darías si avanzas igual?', '¿Qué decisión pequeña puedes tomar hoy?', true),
(10, 'Exploración Auténtica', '<iframe width="315" height="576" src="https://www.youtube.com/embed/_2rBmbReMHc" frameborder="0" allowfullscreen></iframe>', 'Lo que deseas... te desea a ti.', E'1. ¿Cuál es tu deseo más auténtico?\n2. ¿Por qué es importante para ti?\n3. ¿Qué tipo de persona necesitas ser para honrar ese deseo?', '¿Qué vida está intentando nacer en ti?', true),
(11, 'Sanación Interior', '<iframe width="315" height="576" src="https://www.youtube.com/embed/aJUQVSbekok" frameborder="0" allowfullscreen></iframe>', 'Todo lo que sientes... pasará.', E'1. ¿Qué hecho todavía me duele cuando lo recuerdo?\n2. ¿Qué no dije... y todavía llevo por dentro?\n3. ¿De qué manera sigo viviendo desde esa herida hoy?', '¿Qué emoción necesitas permitir?', true),
(12, 'Sanación Interior', '<iframe width="315" height="576" src="https://www.youtube.com/embed/ZmAipKj2NAg" frameborder="0" allowfullscreen></iframe>', 'Reconoce tu frecuencia emocional habitual.', E'1. Cuando algo me duele o me frustra... ¿qué emoción aparece casi siempre?\n2. ¿Desde cuándo recuerdo sentirla con frecuencia?\n3. ¿Cómo ha influido esa emoción en mis decisiones?', '¿Cuál es tu emoción dominante?', true),
(13, 'Sanación Interior', '<iframe width="315" height="576" src="https://www.youtube.com/embed/aXi2iJr_wmk" frameborder="0" allowfullscreen></iframe>', 'Perdonar es soltar la historia que te atrapa.', E'1. ¿A quién o a qué sigo dándole energía cuando lo recuerdo?\n2. ¿Qué emoción se activa todavía cuando pienso en eso?\n3. ¿Qué me ha costado mantener ese resentimiento?', '¿Qué necesitas perdonar para liberarte?', true),
(14, 'Sanación Interior', '<iframe width="315" height="576" src="https://www.youtube.com/embed/nWhb5aOwp9I" frameborder="0" allowfullscreen></iframe>', 'El duelo no se supera: se transforma.', E'1. ¿Qué pérdida todavía me duele cuando la recuerdo?\n2. ¿Qué parte de mí se fue con eso?\n3. ¿Qué no he querido aceptar completamente?', '¿Qué duelo necesitas honrar?', true),
(15, 'Sanación Interior', '<iframe width="315" height="576" src="https://www.youtube.com/embed/hu0rVF0FCAY" frameborder="0" allowfullscreen></iframe>', 'Cultiva el jardín emocional que quieres habitar.', E'1. ¿Qué peso siento que ha empezado a aflojarse estos días?\n2. ¿Qué comprensión nueva tengo sobre mí que antes no veía?\n3. ¿Cómo quiero cuidar mi mundo interior de ahora en adelante?', '¿Qué emoción quieres cultivar?', true),
(16, 'Expansión Existencial', '<iframe width="315" height="576" src="https://www.youtube.com/embed/bSgjliG2gx8" frameborder="0" allowfullscreen></iframe>', 'Manifiesta tu deseo desde dentro hacia afuera.', E'1. ¿Qué área de mi vida está lista para expandirse ahora?\n2. Si ya estuviera viviendo una versión más madura y despierta... ¿cómo actuaría hoy?\n3. ¿Cuál es la acción mínima coherente que puedo hacer hoy?', '¿Qué acción vas a tomar hoy?', true),
(17, 'Expansión Existencial', '<iframe width="315" height="576" src="https://www.youtube.com/embed/cGMsbvKAIbg" frameborder="0" allowfullscreen></iframe>', 'Tus 3 recursos más valiosos: energía, atención y tiempo.', E'1. ¿Qué situaciones o personas drenan mi energía?\n2. ¿Qué hábitos o pensamientos dispersan mi atención?\n3. ¿Qué actividades están ocupando tiempo sin aportar valor real?', '¿Qué fuga de energía vas a cerrar?', true),
(18, 'Expansión Existencial', '<iframe width="315" height="576" src="https://www.youtube.com/embed/ZNLFukus1YI" frameborder="0" allowfullscreen></iframe>', 'Rituales poderosos para sostener tu expansión.', E'1. ¿En qué momento del día puedo detenerme 3 a 5 minutos?\n2. ¿Qué haré en ese espacio?\n3. ¿Cuál será mi ritual mínimo diario?', '¿Cuál es tu ritual de expansión?', true),
(19, 'Optimización Vital', '<iframe width="315" height="576" src="https://www.youtube.com/embed/6Gjz9-FeCvE" frameborder="0" allowfullscreen></iframe>', 'Sintoniza con la vida que deseas crear.', E'1. ¿Qué tono ha dominado mi vida últimamente?\n2. ¿Qué tono quiero habitar desde hoy?\n3. ¿Qué decisión tomaría hoy desde ese tono?', '¿Qué tono elijes para tu vida?', true),
(20, 'Optimización Vital', '<iframe width="315" height="576" src="https://www.youtube.com/embed/uPymaJ3-kEY" frameborder="0" allowfullscreen></iframe>', 'El presente: único lugar donde sucede tu vida.', E'1. ¿Dónde se fue mi atención hoy?\n2. ¿En qué momento estuve realmente presente?\n3. ¿Qué parte de mi vida estoy perdiendo por vivir distraído?', '¿Cómo vuelves al presente hoy?', true),
(21, 'Optimización Vital', '<iframe width="315" height="576" src="https://www.youtube.com/embed/5BP4biina9U" frameborder="0" allowfullscreen></iframe>', 'Trascender: vivir más allá de ti mismo.', E'1. ¿Qué aprendí sobre mí en estos 21 días?\n2. ¿Qué ya no estoy dispuesto a tolerar?\n3. ¿Qué versión de mí elijo habitar desde hoy?', '¿Qué promesa te haces para tu nueva vida?', true),
(22, 'Cierre', '<iframe width="315" height="576" src="https://www.youtube.com/embed/8uwGrrJnTqM" frameborder="0" allowfullscreen></iframe>', 'El ritual de integración: tu nueva vida comienza hoy.', E'1. ¿Cómo sostendrás tu evolución?\n2. ¿Qué siguiente nivel elijes?\n3. ¿Qué compromiso real tomas contigo?', '¿Cuál es tu próximo paso?', true)
ON CONFLICT (day_number) DO UPDATE SET
  stage_name = EXCLUDED.stage_name,
  video_embed_url = EXCLUDED.video_embed_url,
  daily_quote = EXCLUDED.daily_quote,
  questions_text = EXCLUDED.questions_text,
  insight_prompt_text = EXCLUDED.insight_prompt_text,
  is_published = EXCLUDED.is_published;
